### ISSUE TITLE
Update to DotNetCore 1.1.0

### ISSUE THREAD

**Issue by gsacavdm** [Azure-Samples/active-directory-dotnet-webapp-openidconnect-aspnetcore-b2c#10]
Also captured by this UserVoice entry:
https://feedback.azure.com/forums/169401-azure-active-directory/suggestions/17526031

**Comment by gsacavdm** [comment]
See https://github.com/Azure-Samples/active-directory-dotnet-webapp-openidconnect-aspnetcore-b2c/tree/dotnet101

**Comment by gsacavdm** [comment]
See https://github.com/Azure-Samples/active-directory-dotnet-webapp-openidconnect-aspnetcore-b2c/tree/dotnet11

**Comment by NikolaosWakem** [comment]
I have master branch working - but not havin any luck with 1.1.0... Does the dotnet11 branch work?

**Comment by gsacavdm** [comment]
Kudos to @danroth27 for taking care of this with #14
