### ISSUE TITLE
Does this approach of adding users wortk with Graph API?

### ISSUE THREAD

**Issue by BharatRajMeriyala** [Azure-Samples/active-directory-dotnet-webapp-openidconnect-aspnetcore-b2c#11]
Can we add users through Graph API?
Can you kindly provide a sample of achieving the same through Dotnet Core?

**Comment by gsacavdm** [comment]
Yes, you can add users through the Graph, but that's a sample of it's own, unrelated to this one.
For now, we only have a [regular dot net sample](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-devquickstarts-graph-dotnet), though it should work pretty much the same for dotnet core.
