### ISSUE TITLE
Error : InvalidOperationException: No authentication handler is configured to handle the scheme: b2c_1_org_b2c_global_signin

### ISSUE THREAD

**Issue by bobby-ind** [Azure-Samples/active-directory-dotnet-webapp-openidconnect-aspnetcore-b2c#12]
In this sample app there is a Sign-in button. I am able to Sign-in successfully by clicking Sign-In button by providing my Azure B2C Tenant and registering the application in the tenant.

In another app, I want to authenticate without the Sign-In button being clicked i.e. right when I open the URL, I get redirected first to the Azure B2C AD login page, and after successful validation of credentials, I should be able to see the home screen.

So, what I did was from the URL mentioned from the article, I copied the SiginIn() method as:

```
public async Task<IActionResult> Index()
{
    await SignIn();

    await GetDataAsync();
}
```

I get an error message on running the application as : InvalidOperationException: No authentication handler is configured to handle the scheme: b2c_1_org_b2c_global_signin

Please advise how can I authenticate directly without the signin button. Previously with MVC5, I have successfully done this where I used [Authorize] attribute on the Controller class.

**Comment by gsacavdm** [comment]
The error `InvalidOperationException: No authentication handler is configured to handle the scheme: b2c_1_org_b2c_global_signin` indicates that you haven't configured a middleware for that policy.

The scheme provided as the first parameter to the Challenge in the [SignIn method](https://github.com/Azure-Samples/active-directory-dotnet-webapp-openidconnect-aspnetcore-b2c/blob/master/WebApp-OpenIDConnect-DotNet/Controllers/AccountController.cs#L35) should match the scheme provided when configuring the middleware in [Startup.cs](https://github.com/Azure-Samples/active-directory-dotnet-webapp-openidconnect-aspnetcore-b2c/blob/master/WebApp-OpenIDConnect-DotNet/Startup.cs#L98).

All that aside, you shouldn't need to explicitly call out await SignIn in your Index, provided you configure your middleware correctly as per the sample, just adding the [Authorize] attribute will force the user to sign-in.
