### ISSUE TITLE
PostLogoutRedirectUri / RedirectUri

### ISSUE THREAD

**Issue by renevangeffen** [Azure-Samples/active-directory-dotnet-webapp-openidconnect-aspnetcore-b2c#3]
RedirectUri = Configuration["AzureAD:RedirectUri"]; in Startup.cs refers to AzureAD:RedirectUri from config.json, however config.json does not contain AzureAD:RedirectUri. only a AzureAD:PostLogoutRedirectUri

**Comment by dstrockis** [comment]
Fixed in commit 8993f0f26aff8af0766dffd5862a910e74ff396c
