### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by himadrinath** [Azure-Samples/active-directory-dotnet-webapp-openidconnect-aspnetcore-b2c#4]
@dstrockis  string scheme = (HttpContext.User.FindFirst("http://schemas.microsoft.com/claims/authnclassreference"))?.Value;

getting null

**Comment by jpgutton** [comment]
I have the same issue and can't figure out how to logout correctly

**Comment by fp0n** [comment]
I was able to get this working properly by using "tfp" as the string - the main thing is that the class is trying to determine what policy did the user login under (B2C_1_sign_in, B2C_1_sign_up, B2C_1_sign_up_or_sign_in, etc.) and logout out of that policy - at least that worked for me.

**Comment by KevinOrtman** [comment]
I added [https://github.com/Azure-Samples/active-directory-dotnet-webapp-openidconnect-aspnetcore-b2c/pull/8](a pull request) which should correct this issue.

**Comment by gsacavdm** [comment]
Thanks @KevinOrtman for your fix. That'll close this issue.
