### ISSUE TITLE
Fail to invoke B2C workflow

### ISSUE THREAD

**Issue by jskulavik** [Azure-Samples/active-directory-dotnet-webapp-openidconnect-aspnetcore-b2c#5]
Hi Folks,

No matter how I configure the cloned app (fabrikam) or my own tenancy, the sample fails to direct to the login.microsoft.com/[xxxxxxx] uri.  Is there something in this sample that requires updating?  I'd be glad to create a PR, but I'm not sure where to determine where the issue with this sample is.  Thanks!

**Comment by Arksutw** [comment]
In config.json, chanage PostLogoutRedirectUri to RedirectUri and it will run as well as you expect.

**Comment by dstrockis** [comment]
Fixed in 8993f0f26aff8af0766dffd5862a910e74ff396c
