### ISSUE TITLE
Compatibility with .NET Core 3.1

### ISSUE THREAD

**Issue by pawlikowski-michal** [Azure-Samples/active-directory-dotnet-webapp-openidconnect-aspnetcore-b2c#89]
Hi,
This sample seems not to be compatible with newest .net core 3.1.
Can you please update the sample?
Thanks

**Comment by TiagoBrenck** [comment]
@pawlikowski-michal could you refer to this sample instead? https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API/4-2-B2C

**Comment by jmprieur** [comment]
Closing this issue as this sample is being archived and replaced by a newer ASP.NET Core 3.1 sample.
See Readme.md
