### ISSUE TITLE
How do I diagnose errors? 

### ISSUE THREAD

**Issue by MichielCornilleESC** [Azure-Samples/active-directory-dotnet-webapp-openidconnect-aspnetcore-b2c#90]
Suddenly, after messing with custom policies for a bit, my Azure B2C tenant started throwing

> **AADB2C90085**: The service has encountered an internal error. Please reauthenticate and try again. 

This happens when I try to sign in to my application. (It creates the new user during signin/signup, but when returning to the dotnetcore app I just get this error 

Here's what I tried:
-  I reverted my policy code to what worked before
-  I used fiddler to get a better look at server responses which gave no valuable information whatsoever.
- I linked my custom policy to application insights to trace my user journey, and used the wingtipsb2c user journey viewer to see what was in the traces, all green, no errors in sight.

Is there no way to just see the stack trace of the internal error?

Thanks in advance!

**Comment by mmacy** [comment]
Hi @MichielCornilleESC, I notice that you've closed this, but for future reference, here's an article about using Application Insights to help troubleshoot B2C errors:

https://docs.microsoft.com/azure/active-directory-b2c/troubleshoot-with-application-insights
