### ISSUE TITLE
How to pass domain_hint while calling B2C for login

### ISSUE THREAD

**Issue by yashwanth-yenugu** [Azure-Samples/active-directory-dotnet-webapp-openidconnect-aspnetcore-b2c#91]
Where can I pass domain_hint?

**Comment by jmprieur** [comment]
What is your scenario
Would you want to try to override the OnRedirectToIdenitityProvider event?

   services.Configure<OpenIdConnectOptions>(AzureADDefaults.OpenIdScheme, options =>
    {
        ...
        // Attempt to avoid displaying the select account dialog when signing out
        options.Events.OnRedirectToIdentityProvider = async context =>
        {
            //Your logic here
            context.ProtocolMessage.DomainHint = user.GetDomainHint();
            await Task.FromResult(0);
        };
    }
